### ISSUE TITLE
Upload file to Revit Server

### ISSUE THREAD

**Issue by naumanmy** [pyrevitlabs/rpws#2]
Thanks for the great tool
Is there any way we can get support for uploading files to Revit Server.

**Comment by eirannejad** [comment]
The models needs to be saved to Revit server from inside Revit. As far as I know, Revit server api does not allow external file uploads

**Comment by dronov-dmitry** [comment]
Hallo, how can i save file to revit server? 
Is it possible with rpws?
Can you please make it?

**Comment by jmcouffin** [comment]
like said by Ehsan, this needs to happen within revit 
https://thebuildingcoder.typepad.com/blog/2013/12/saving-a-new-central-file-to-revit-server.html#3

**Comment by dronov-dmitry** [comment]
> like said by Ehsan, this needs to happen within revit 

Thank you, Jean-Marc
Yes, i saw this issue, but unfortunately i have problem on Revit server with "SaveAs()".

Revit said : "The server-based central model could not be accessed because of a network communication error" and don't write file on server (only in root folder). Unfortunately i can't fix this problem and was hoped that RPWS can fix that, but as i understand it's impossible.
